//! Lean Proof Domain Adapter for NPE
//!
//! This adapter allows the NPE to generate Lean proof candidates,
//! then verifies them through Lean.
//!
//! The pipeline is:
//!   NPE generates proof attempts
//!   → Lean/RV verification
//!   → Genesis metrics  
//!   → Formation admission
//!   → Best verified proof selected

use serde::{Deserialize, Serialize};


/// Proof candidate generated by the NPE
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofCandidate {
    pub id: String,
    pub wildness: f64,
    pub target_theorem: String,
    pub proof_text: String,
    pub proof_tactics: Vec<String>,
    pub tactic_count: usize,
    pub helper_lemmas: usize,
    pub imports: Vec<String>,
    pub novelty: f64,
}

/// Lean verification report
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct LeanVerificationReport {
    pub compiles: bool,
    pub has_sorry: bool,
    pub has_admit: bool,
    pub new_axioms: usize,
    pub statement_unchanged: bool,
    pub forbidden_imports: bool,

    pub build_time_ms: u64,
    pub errors: Vec<String>,
    pub warnings: usize,

    pub genesis_margin: i128,
    pub coherence_margin: i128,
    pub formation_accept: bool,
    /// Detailed failure report
    pub failure_report: Option<crate::failure_taxonomy::FailureReport>,
}

/// Compute Genesis metrics for a proof
pub fn compute_genesis_metrics(candidate: &ProofCandidate) -> (u128, u128, u128) {
    // M(t'): proof complexity after
    let proof_complexity = compute_proof_complexity(candidate);

    // C(p): generation cost
    let cost = candidate.tactic_count as u128 * 5
        + candidate.helper_lemmas as u128 * 20
        + candidate.imports.len() as u128 * 10;

    // D(p): defect budget based on wildness
    let defect = 50 + (candidate.wildness * 10.0) as u128;

    (proof_complexity, cost, defect)
}

/// Compute proof complexity
fn compute_proof_complexity(candidate: &ProofCandidate) -> u128 {
    let mut complexity = 0u128;

    // Base complexity from proof length
    complexity += candidate.proof_text.len() as u128;

    // Add weight for tactics
    complexity += candidate.tactic_count as u128 * 10;

    // Add helper lemma complexity
    complexity += candidate.helper_lemmas as u128 * 30;

    // Add import complexity
    complexity += candidate.imports.len() as u128 * 50;

    // Penalize "sorry" usage heavily
    if candidate.proof_text.contains("sorry") {
        complexity += 1000;
    }

    // Penalize "admit" usage
    if candidate.proof_text.contains("admit") {
        complexity += 500;
    }

    complexity
}

/// Compute Coherence metrics for a proof
pub fn compute_coherence_metrics(report: &LeanVerificationReport) -> (u128, u128, u128) {
    // V(y): post-proof risk
    let mut risk = 0u128;
    if !report.compiles {
        risk += 100;
    }
    if report.has_sorry {
        risk += 500;
    }
    if report.has_admit {
        risk += 300;
    }
    risk += report.new_axioms as u128 * 100;
    if report.forbidden_imports {
        risk += 200;
    }
    risk += report.warnings as u128 * 2;

    // Spend(R): execution cost
    let spend = (report.build_time_ms / 100) as u128;

    // Defect(R): allowed budget
    let defect = 50; // base budget

    (risk, spend, defect)
}

/// Check if candidate is formation-admissible
pub fn is_formation_admissible(
    candidate: &ProofCandidate,
    base_complexity: u128,
    report: &LeanVerificationReport,
) -> (bool, i128, i128) {
    let (m_after, cost, defect) = compute_genesis_metrics(candidate);
    let genesis_margin = base_complexity as i128 + defect as i128 - m_after as i128 - cost as i128;

    let (risk, spend, def) = compute_coherence_metrics(report);
    let coherence_margin = risk as i128 + def as i128 - spend as i128;

    let formation_accept = genesis_margin >= 0
        && report.compiles
        && !report.has_sorry
        && !report.has_admit
        && !report.forbidden_imports
        && coherence_margin >= 0;

    (formation_accept, genesis_margin, coherence_margin)
}

/// First failure classification for proofs
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProofFirstFailure {
    Accepted,
    Genesis,
    Compiles,
    Sorry,
    Admit,
    StatementChanged,
    ForbiddenImport,
    Coherence,
}

impl ProofFirstFailure {
    pub fn classify(
        genesis_margin: i128,
        report: &LeanVerificationReport,
        coherence_margin: i128,
    ) -> Self {
        // First check Genesis
        if genesis_margin < 0 {
            return ProofFirstFailure::Genesis;
        }
        // Then verification checks
        if !report.compiles {
            return ProofFirstFailure::Compiles;
        }
        if report.has_sorry {
            return ProofFirstFailure::Sorry;
        }
        if report.has_admit {
            return ProofFirstFailure::Admit;
        }
        if !report.statement_unchanged {
            return ProofFirstFailure::StatementChanged;
        }
        if report.forbidden_imports {
            return ProofFirstFailure::ForbiddenImport;
        }
        // Finally check Coherence
        if coherence_margin < 0 {
            return ProofFirstFailure::Coherence;
        }
        ProofFirstFailure::Accepted
    }
}

/// Proof policy configuration
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofPolicy {
    pub allow_sorry: bool,
    pub allow_admit: bool,
    pub allow_new_axioms: bool,
    pub allow_forbidden_imports: bool,
    pub max_tactic_count: usize,
    pub max_helper_lemmas: usize,
    pub max_proof_length: usize,
}

impl Default for ProofPolicy {
    fn default() -> Self {
        ProofPolicy {
            allow_sorry: false,
            allow_admit: false,
            allow_new_axioms: false,
            allow_forbidden_imports: false,
            max_tactic_count: 100,
            max_helper_lemmas: 10,
            max_proof_length: 5000,
        }
    }
}

/// Proof selection mode
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq, Eq)]
pub enum ProofSelectorMode {
    /// Maximizes novelty with safety margin
    SafeNovel,
    /// Maximizes novelty near boundary
    Edge,
    /// Finds near-boundary still-admissible
    NearBoundary,
}

/// Formation result for proofs
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ProofFormationResult {
    pub candidate_id: String,
    pub formation_accept: bool,
    pub first_failure: ProofFirstFailure,

    pub genesis_margin: i128,
    pub coherence_margin: i128,
    pub boundary_margin: i128,

    pub novelty: f64,
    pub safe_score: f64,
    pub edge_score: f64,

    pub report: LeanVerificationReport,
}

/// Build formation result for a proof
pub fn build_formation_result(
    candidate: &ProofCandidate,
    base_complexity: u128,
    report: &LeanVerificationReport,
    _mode: &ProofSelectorMode,
    alpha: f64,
) -> ProofFormationResult {
    let (m_after, cost, defect) = compute_genesis_metrics(candidate);
    let genesis_margin = base_complexity as i128 + defect as i128 - m_after as i128 - cost as i128;

    let (risk, spend, def) = compute_coherence_metrics(report);
    let coherence_margin = risk as i128 + def as i128 - spend as i128;

    let boundary_margin = genesis_margin.min(coherence_margin);

    let safe_score = candidate.novelty + alpha * boundary_margin as f64;
    let edge_score = candidate.novelty - alpha * boundary_margin as f64;

    let formation_accept = genesis_margin >= 0
        && report.compiles
        && !report.has_sorry
        && !report.has_admit
        && coherence_margin >= 0;

    let first_failure = ProofFirstFailure::classify(genesis_margin, report, coherence_margin);

    ProofFormationResult {
        candidate_id: candidate.id.clone(),
        formation_accept,
        first_failure,
        genesis_margin,
        coherence_margin,
        boundary_margin,
        novelty: candidate.novelty,
        safe_score,
        edge_score,
        report: report.clone(),
    }
}

/// Proof class selection for diverse generation
#[derive(Clone, Debug, PartialEq)]
pub enum ProofClass {
    Direct,        // direct tactic application
    HelperLemma,   // adds helper lemmas
    Simplify,      // adds simp/rw lemmas
    Cases,         // adds cases/hypothesis
    Induction,     // adds induction
    LibrarySearch, // imports from Mathlib
    Weaken,        // uses sorry/admit
    Refactor,      // refactors existing proof
}

impl ProofClass {
    pub fn select(wildness: f64, rand: f64) -> Self {
        if wildness < 0.5 {
            if rand < 0.7 {
                ProofClass::Direct
            } else {
                ProofClass::Refactor
            }
        } else if wildness < 1.5 {
            if rand < 0.5 {
                ProofClass::Direct
            } else if rand < 0.8 {
                ProofClass::HelperLemma
            } else {
                ProofClass::Refactor
            }
        } else if wildness < 2.5 {
            if rand < 0.3 {
                ProofClass::Direct
            } else if rand < 0.5 {
                ProofClass::HelperLemma
            } else if rand < 0.7 {
                ProofClass::Simplify
            } else if rand < 0.85 {
                ProofClass::Induction
            } else if rand < 0.95 {
                ProofClass::LibrarySearch
            } else {
                ProofClass::Weaken
            }
        } else {
            // High wildness - more aggressive
            if rand < 0.2 {
                ProofClass::HelperLemma
            } else if rand < 0.4 {
                ProofClass::Cases
            } else if rand < 0.6 {
                ProofClass::Induction
            } else if rand < 0.8 {
                ProofClass::LibrarySearch
            } else {
                ProofClass::Weaken
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_genesis_metrics() {
        let candidate = ProofCandidate {
            id: "proof-1".to_string(),
            wildness: 1.0,
            target_theorem: "target".to_string(),
            proof_text: "apply h1".to_string(),
            proof_tactics: vec!["apply".to_string()],
            tactic_count: 1,
            helper_lemmas: 0,
            imports: vec![],
            novelty: 1.0,
        };

        let (m_after, cost, _) = compute_genesis_metrics(&candidate);
        assert!(m_after > 0);
        assert!(cost > 0);
    }

    #[test]
    fn test_formation_admissible() {
        let candidate = ProofCandidate {
            id: "proof-1".to_string(),
            wildness: 1.0,
            target_theorem: "target".to_string(),
            proof_text: "exact dec_trivial".to_string(),
            proof_tactics: vec!["exact".to_string()],
            tactic_count: 1,
            helper_lemmas: 0,
            imports: vec![],
            novelty: 1.0,
        };

        let report = LeanVerificationReport {
            compiles: true,
            has_sorry: false,
            has_admit: false,
            new_axioms: 0,
            statement_unchanged: true,
            forbidden_imports: false,
            build_time_ms: 500,
            errors: vec![],
            warnings: 0,
            genesis_margin: 0,
            coherence_margin: 0,
            formation_accept: false,
            failure_report: None,
        };

        let (accept, gen_m, _) = is_formation_admissible(&candidate, 1000, &report);
        assert!(accept);
        assert!(gen_m > 0);
    }
}
