//! NPE Wildness Candidate Structures
//!
//! Data structures for the NPE Wildness Boundary Test:
//! - GenesisCandidate: forward generation candidate with Genesis and Coherence metrics
//! - ProjectedCohClaim: projected Coherence claim after transformation
//! - WildnessLevel: wildness parameter wrapper
//! - WildnessResult: aggregated results for a wildness level

use serde::{Deserialize, Serialize};

/// Projected Coherence Claim
///
/// After a Genesis candidate is projected through Π, we get a Coherence claim
/// with valuation metrics, spend, and defect information.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
pub struct ProjectedCohClaim {
    /// V(x): valuation of the state before execution
    pub v_before: u128,
    /// V(y): valuation of the state after execution
    pub v_after: u128,
    /// Spend(R): execution cost
    pub spend: u128,
    /// Defect(R): allowed defect budget during execution
    pub defect: u128,
    /// RV accept/reject result
    pub rv_accept: bool,
}

impl ProjectedCohClaim {
    pub fn new(v_before: u128, v_after: u128, spend: u128, defect: u128, rv_accept: bool) -> Self {
        Self {
            v_before,
            v_after,
            spend,
            defect,
            rv_accept,
        }
    }
}

/// Genesis Candidate for NPE generation
///
/// A candidate generated by the NPE with:
/// - Genesis metrics: M(g), M(g'), C(p), D(p)
/// - projected Coherence metrics: V(x), V(y), Spend(R), Defect(R)
/// - novelty: structural distance from baseline
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct GenesisCandidate {
    /// Unique identifier
    pub id: String,
    /// Wildness level that generated this candidate
    pub wildness: f64,

    /// M(g): complexity before generation
    pub m_before: u128,
    /// M(g'): complexity after generation
    pub m_after: u128,
    /// C(p): generation cost
    pub generation_cost: u128,
    /// D(p): generation defect budget
    pub generation_defect: u128,

    /// Novelty score: structural distance from baseline
    pub novelty: f64,

    /// Projected Coherence claim
    pub projection: ProjectedCohClaim,
}

impl GenesisCandidate {
    pub fn new(
        id: String,
        wildness: f64,
        m_before: u128,
        m_after: u128,
        generation_cost: u128,
        generation_defect: u128,
        novelty: f64,
        projection: ProjectedCohClaim,
    ) -> Self {
        Self {
            id,
            wildness,
            m_before,
            m_after,
            generation_cost,
            generation_defect,
            novelty,
            projection,
        }
    }

    /// Genesis margin: Δ_Gen = M(g) + D(p) - M(g') - C(p)
    ///
    /// Positive margin means Genesis-admissible.
    pub fn genesis_margin(&self) -> i128 {
        (self.m_before as i128 + self.generation_defect as i128)
            - (self.m_after as i128 + self.generation_cost as i128)
    }

    /// Check if candidate is Genesis-admissible
    pub fn is_genesis_admissible(&self) -> bool {
        self.genesis_margin() >= 0
    }

    /// Coherence margin: Δ_Coh = V(x) + Defect(R) - V(y) - Spend(R)
    ///
    /// Positive margin means Coherence-admissible.
    pub fn coherence_margin(&self) -> i128 {
        let p = &self.projection;
        (p.v_before as i128 + p.defect as i128) - (p.v_after as i128 + p.spend as i128)
    }

    /// Check if candidate is Coherence-admissible
    pub fn is_coh_admissible(&self) -> bool {
        self.projection.rv_accept && self.coherence_margin() >= 0
    }

    /// Check if candidate is Formation-admissible (both Genesis and Coherence)
    pub fn is_formation_admissible(&self) -> bool {
        self.is_genesis_admissible() && self.is_coh_admissible()
    }
}

/// Wildness Level wrapper
#[derive(Clone, Copy, Debug, PartialEq, PartialOrd)]
pub struct WildnessLevel(pub f64);

impl WildnessLevel {
    pub fn new(lambda: f64) -> Self {
        Self(lambda)
    }

    pub fn value(&self) -> f64 {
        self.0
    }
}

impl Default for WildnessLevel {
    fn default() -> Self {
        Self(1.0)
    }
}

/// First failure classification - which verifier gate stops the candidate first
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FirstFailure {
    None,
    Genesis,
    Rv,
    Coh,
}

impl FirstFailure {
    pub fn classify(c: &GenesisCandidate) -> Self {
        let genesis_ok = c.is_genesis_admissible();
        let rv_ok = c.projection.rv_accept;
        let coh_ok = if rv_ok {
            c.coherence_margin() >= 0
        } else {
            false
        };

        if !genesis_ok {
            FirstFailure::Genesis
        } else if !rv_ok {
            FirstFailure::Rv
        } else if !coh_ok {
            FirstFailure::Coh
        } else {
            FirstFailure::None // Accepted
        }
    }
}

/// Wildness sweep result for a single wildness level
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct WildnessResult {
    /// Wildness level
    pub wildness: f64,
    /// Total candidates generated
    pub total: usize,

    /// Genesis acceptance rate
    pub genesis_accept_rate: f64,
    /// Coherence acceptance rate
    pub coh_accept_rate: f64,
    /// Formation acceptance rate
    pub formation_accept_rate: f64,

    /// Average novelty across all candidates
    pub avg_novelty_all: f64,
    /// Average novelty across accepted candidates
    pub avg_novelty_accepted: f64,
    /// Wildness yield: acceptance_rate × avg_novelty_accepted
    pub wildness_yield: f64,

    /// Genesis rejection count
    pub genesis_rejects: usize,
    /// RV rejection count
    pub rv_rejects: usize,
    /// Coherence rejection count (Genesis OK but Coherence fails)
    pub coherence_rejects: usize,

    /// First-failure counts
    pub first_genesis_count: usize,
    pub first_rv_count: usize,
    pub first_coh_count: usize,
    pub accepted_count: usize,

    /// Boundary margin stats for accepted candidates
    pub avg_genesis_margin_accepted: f64,
    pub avg_coh_margin_accepted: f64,
    pub min_boundary_margin_accepted: i128,
    pub near_boundary_percent: f64,
}

impl WildnessResult {
    pub fn new(
        wildness: f64,
        total: usize,
        genesis_accepts: usize,
        coh_accepts: usize,
        formation_accepts: usize,
        novelty_sum_all: f64,
        novelty_sum_accepted: f64,
        genesis_rejects: usize,
        rv_rejects: usize,
        coherence_rejects: usize,
        first_genesis_count: usize,
        first_rv_count: usize,
        first_coh_count: usize,
        accepted_count: usize,
        avg_genesis_margin: f64,
        avg_coh_margin: f64,
        min_boundary_margin: i128,
        near_boundary_count: usize,
    ) -> Self {
        let total_f = total as f64;
        let avg_novelty_all = if total > 0 {
            novelty_sum_all / total_f
        } else {
            0.0
        };
        let avg_novelty_accepted = if formation_accepts > 0 {
            novelty_sum_accepted / formation_accepts as f64
        } else {
            0.0
        };
        let formation_rate = formation_accepts as f64 / total_f;
        let wildness_yield = formation_rate * avg_novelty_accepted;
        let near_boundary_percent = if accepted_count > 0 {
            near_boundary_count as f64 / accepted_count as f64 * 100.0
        } else {
            0.0
        };

        Self {
            wildness,
            total,
            genesis_accept_rate: genesis_accepts as f64 / total_f,
            coh_accept_rate: coh_accepts as f64 / total_f,
            formation_accept_rate: formation_rate,
            avg_novelty_all,
            avg_novelty_accepted,
            wildness_yield,
            genesis_rejects,
            rv_rejects,
            coherence_rejects,
            first_genesis_count,
            first_rv_count,
            first_coh_count,
            accepted_count,
            avg_genesis_margin_accepted: avg_genesis_margin,
            avg_coh_margin_accepted: avg_coh_margin,
            min_boundary_margin_accepted: min_boundary_margin,
            near_boundary_percent,
        }
    }

    /// Get the top rejection reason
    pub fn top_rejection(&self) -> &'static str {
        if self.genesis_rejects >= self.rv_rejects && self.genesis_rejects >= self.coherence_rejects
        {
            "GenesisViolation"
        } else if self.rv_rejects >= self.coherence_rejects {
            "RVReject"
        } else {
            "CohViolation"
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Test: Genesis margin calculation
    #[test]
    fn test_genesis_margin_positive() {
        let candidate = GenesisCandidate::new(
            "test-1".to_string(),
            1.0,
            1000, // m_before
            800,  // m_after - decreased
            50,   // generation_cost
            100,  // generation_defect - slack
            1.0,  // novelty
            ProjectedCohClaim::default(),
        );

        // 1000 + 100 - 800 - 50 = 250 > 0
        assert!(candidate.genesis_margin() > 0);
        assert!(candidate.is_genesis_admissible());
    }

    /// Test: Genesis margin negative (not admissible)
    #[test]
    fn test_genesis_margin_negative() {
        let candidate = GenesisCandidate::new(
            "test-2".to_string(),
            5.0,
            1000, // m_before
            1200, // m_after - increased
            100,  // generation_cost
            50,   // generation_defect - low slack
            5.0,  // novelty
            ProjectedCohClaim::default(),
        );

        // 1000 + 50 - 1200 - 100 = -250 < 0
        assert!(candidate.genesis_margin() < 0);
        assert!(!candidate.is_genesis_admissible());
    }

    /// Test: Coherence margin
    #[test]
    fn test_coherence_margin() {
        let projection = ProjectedCohClaim::new(
            1000, // v_before
            800,  // v_after - decreased
            50,   // spend
            100,  // defect
            true, // rv_accept
        );

        let candidate = GenesisCandidate::new(
            "test-3".to_string(),
            1.0,
            1000,
            800,
            50,
            100,
            1.0,
            projection,
        );

        // 1000 + 100 - 800 - 50 = 250 > 0
        assert!(candidate.coherence_margin() > 0);
        assert!(candidate.is_coh_admissible());
    }

    /// Test: Formation admissibility requires both Genesis and Coherence
    #[test]
    fn test_formation_admissible() {
        let projection = ProjectedCohClaim::new(1000, 800, 50, 100, true);

        let candidate = GenesisCandidate::new(
            "test-4".to_string(),
            1.0,
            1000,
            800,
            50,
            100, // Genesis OK
            1.0,
            projection, // Coherence OK
        );

        assert!(candidate.is_formation_admissible());
    }

    /// Test: Formation fails if Genesis fails
    #[test]
    fn test_formation_fails_genesis() {
        let projection = ProjectedCohClaim::new(1000, 800, 50, 100, true);

        let candidate = GenesisCandidate::new(
            "test-5".to_string(),
            5.0,
            1000,
            1200,
            100,
            50, // Genesis FAILS
            5.0,
            projection, // Coherence OK
        );

        assert!(!candidate.is_formation_admissible());
    }

    /// Test: Formation fails if Coherence fails
    #[test]
    fn test_formation_fails_coherence() {
        let projection = ProjectedCohClaim::new(
            1000, 1200, 50, 100, true, // Coherence FAILS
        );

        let candidate = GenesisCandidate::new(
            "test-6".to_string(),
            1.0,
            1000,
            800,
            50,
            100, // Genesis OK
            1.0,
            projection,
        );

        assert!(!candidate.is_formation_admissible());
    }

    /// Test: WildnessResult calculation
    #[test]
    fn test_wildness_result() {
        let result = WildnessResult::new(
            2.0, 100, 62, 58, 41, 780.0, 319.8, 38, 42, 17, 30, 40, 12, 41, 12.5, 8.3, 2, 10,
        );

        assert!((result.genesis_accept_rate - 0.62).abs() < 0.001);
        assert!((result.formation_accept_rate - 0.41).abs() < 0.001);
        assert!((result.wildness_yield - 3.201).abs() < 0.01);
    }
}
